export interface Patient {
  id: string; mrn: string; firstName: string; lastName: string; dob: string; gender: string;
  bloodType: string; allergies: string[]; conditions: string[]; medications: { name: string; dosage: string; frequency: string }[];
  phone: string; email: string; address: string; insurance: string; provider: string;
  lastVisit: string; nextAppointment: string; status: 'active' | 'inactive' | 'new';
}

export interface Appointment {
  id: string; patientId: string; patientName: string; doctorName: string; department: string;
  type: 'checkup' | 'followup' | 'emergency' | 'surgery' | 'consultation' | 'lab';
  date: string; time: string; duration: number; status: 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
  notes: string; location: string; vitals?: { bp: string; hr: number; temp: number; weight: number };
}

export interface MedicalRecord {
  id: string; patientId: string; type: 'lab_result' | 'imaging' | 'note' | 'report' | 'vaccination' | 'prescription';
  title: string; description: string; date: string; provider: string; department: string;
  status: 'final' | 'preliminary' | 'amended'; attachments: number; url: string;
}

export interface Prescription {
  id: string; patientId: string; patientName: string; medication: string; dosage: string;
  frequency: string; route: string; quantity: number; refills: number;
  prescribedBy: string; date: string; status: 'active' | 'discontinued' | 'expired' | 'pending';
  notes: string; pharmacy: string;
}

export interface Message {
  id: string; from: string; to: string; subject: string; content: string;
  timestamp: string; priority: 'routine' | 'urgent' | 'critical'; read: boolean;
  category: 'clinical' | 'administrative' | 'lab' | 'billing'; patientName?: string;
}

export interface TelemedicineSession {
  id: string; patientName: string; doctorName: string; date: string; time: string;
  status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled'; duration: number;
  type: 'video' | 'phone'; notes: string; recording: boolean;
}

export const patients: Patient[] = [
  { id: 'P001', mrn: 'MRN-88472', firstName: 'Sarah', lastName: 'Chen', dob: '1985-03-15', gender: 'Female', bloodType: 'A+', allergies: ['Penicillin', 'Sulfa'], conditions: ['Hypertension', 'Type 2 Diabetes'], medications: [{ name: 'Lisinopril', dosage: '10mg', frequency: 'Once daily' }, { name: 'Metformin', dosage: '500mg', frequency: 'Twice daily' }], phone: '(555) 123-4567', email: 'sarah.chen@email.com', address: '123 Oak St, Portland, OR 97201', insurance: 'Blue Cross BCBS', provider: 'Dr. Vibhanshu Buldeo', lastVisit: '2026-05-10', nextAppointment: '2026-06-15', status: 'active' },
  { id: 'P002', mrn: 'MRN-88473', firstName: 'Robert', lastName: 'Martinez', dob: '1958-11-02', gender: 'Male', bloodType: 'O-', allergies: ['Aspirin'], conditions: ['Coronary Artery Disease', 'Hyperlipidemia', 'GERD'], medications: [{ name: 'Atorvastatin', dosage: '20mg', frequency: 'Once daily' }, { name: 'Omeprazole', dosage: '40mg', frequency: 'Once daily' }, { name: 'Aspirin', dosage: '81mg', frequency: 'Once daily' }], phone: '(555) 234-5678', email: 'robert.martinez@email.com', address: '456 Pine Ave, Portland, OR 97202', insurance: 'Medicare Part D', provider: 'Dr. Emily Park', lastVisit: '2026-05-08', nextAppointment: '2026-07-20', status: 'active' },
  { id: 'P003', mrn: 'MRN-88474', firstName: 'Emily', lastName: 'Johnson', dob: '1992-07-22', gender: 'Female', bloodType: 'B+', allergies: ['Latex', 'Codeine'], conditions: ['Asthma', 'Seasonal Allergies'], medications: [{ name: 'Albuterol HFA', dosage: '90mcg', frequency: 'As needed' }, { name: 'Fluticasone', dosage: '50mcg', frequency: 'Twice daily' }], phone: '(555) 345-6789', email: 'emily.johnson@email.com', address: '789 Cedar Ln, Portland, OR 97203', insurance: 'Aetna', provider: 'Dr. Vibhanshu Buldeo', lastVisit: '2026-04-25', nextAppointment: '2026-06-10', status: 'active' },
  { id: 'P004', mrn: 'MRN-88475', firstName: 'James', lastName: 'Thompson', dob: '1972-09-10', gender: 'Male', bloodType: 'AB+', allergies: [], conditions: ['Lower Back Pain', 'Anxiety'], medications: [{ name: 'Ibuprofen', dosage: '600mg', frequency: 'Three times daily' }, { name: 'Sertraline', dosage: '50mg', frequency: 'Once daily' }], phone: '(555) 456-7890', email: 'james.thompson@email.com', address: '321 Birch St, Portland, OR 97204', insurance: 'Cigna', provider: 'Dr. Michael Torres', lastVisit: '2026-05-01', nextAppointment: '2026-06-22', status: 'active' },
  { id: 'P005', mrn: 'MRN-88476', firstName: 'Maria', lastName: 'Garcia', dob: '1965-01-30', gender: 'Female', bloodType: 'O+', allergies: ['Sulfa'], conditions: ['Hypothyroidism', 'Osteoarthritis', 'Hypertension'], medications: [{ name: 'Levothyroxine', dosage: '75mcg', frequency: 'Once daily' }, { name: 'Losartan', dosage: '50mg', frequency: 'Once daily' }, { name: 'Acetaminophen', dosage: '500mg', frequency: 'As needed' }], phone: '(555) 567-8901', email: 'maria.garcia@email.com', address: '654 Walnut Dr, Portland, OR 97205', insurance: 'United Healthcare', provider: 'Dr. Emily Park', lastVisit: '2026-05-12', nextAppointment: '2026-08-05', status: 'active' },
  { id: 'P006', mrn: 'MRN-88477', firstName: 'David', lastName: 'Kim', dob: '1990-06-18', gender: 'Male', bloodType: 'A-', allergies: ['Peanuts'], conditions: ['Eczema'], medications: [{ name: 'Triamcinolone 0.1%', dosage: 'Apply thin layer', frequency: 'Twice daily' }], phone: '(555) 678-9012', email: 'david.kim@email.com', address: '987 Elm St, Portland, OR 97206', insurance: 'Kaiser Permanente', provider: 'Dr. Sarah Patel', lastVisit: '2026-04-15', nextAppointment: '2026-07-10', status: 'active' },
  { id: 'P007', mrn: 'MRN-88478', firstName: 'Linda', lastName: 'Brown', dob: '1948-12-05', gender: 'Female', bloodType: 'B-', allergies: ['Morphine'], conditions: ['Congestive Heart Failure', 'COPD', 'Type 2 Diabetes'], medications: [{ name: 'Furosemide', dosage: '40mg', frequency: 'Twice daily' }, { name: 'Metformin', dosage: '1000mg', frequency: 'Twice daily' }, { name: 'Tiotropium', dosage: '18mcg', frequency: 'Once daily' }], phone: '(555) 789-0123', email: 'linda.brown@email.com', address: '147 Maple Ave, Portland, OR 97207', insurance: 'Medicare', provider: 'Dr. Vibhanshu Buldeo', lastVisit: '2026-05-05', nextAppointment: '2026-06-28', status: 'active' },
  { id: 'P008', mrn: 'MRN-88479', firstName: 'Michael', lastName: 'Patel', dob: '2000-04-08', gender: 'Male', bloodType: 'AB-', allergies: [], conditions: ['ACL Tear'], medications: [{ name: 'Naproxen', dosage: '500mg', frequency: 'Twice daily' }], phone: '(555) 890-1234', email: 'michael.patel@email.com', address: '258 Spruce Ct, Portland, OR 97208', insurance: 'Aetna', provider: 'Dr. Michael Torres', lastVisit: '2026-05-14', nextAppointment: '2026-06-05', status: 'active' },
  { id: 'P009', mrn: 'MRN-88480', firstName: 'Jennifer', lastName: 'Williams', dob: '1988-08-25', gender: 'Female', bloodType: 'A+', allergies: ['Amoxicillin'], conditions: ['Migraine', 'Iron Deficiency Anemia'], medications: [{ name: 'Sumatriptan', dosage: '50mg', frequency: 'As needed' }, { name: 'Ferrous Sulfate', dosage: '325mg', frequency: 'Once daily' }], phone: '(555) 901-2345', email: 'jennifer.williams@email.com', address: '369 Redwood Dr, Portland, OR 97209', insurance: 'Blue Cross BCBS', provider: 'Dr. Sarah Patel', lastVisit: '2026-04-30', nextAppointment: '2026-07-15', status: 'active' },
  { id: 'P010', mrn: 'MRN-88481', firstName: 'William', lastName: 'Davis', dob: '1975-10-14', gender: 'Male', bloodType: 'O+', allergies: ['Penicillin'], conditions: ['Gout', 'Hypertension'], medications: [{ name: 'Allopurinol', dosage: '300mg', frequency: 'Once daily' }, { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily' }], phone: '(555) 012-3456', email: 'william.davis@email.com', address: '741 Ash Blvd, Portland, OR 97210', insurance: 'Cigna', provider: 'Dr. Emily Park', lastVisit: '2026-05-07', nextAppointment: '2026-08-12', status: 'active' },
  { id: 'P011', mrn: 'MRN-88482', firstName: 'Sophia', lastName: 'Anderson', dob: '2023-02-14', gender: 'Female', bloodType: 'A+', allergies: [], conditions: ['Well Child'], medications: [], phone: '(555) 123-9876', email: 'sophia.anderson@email.com', address: '852 Fir Ln, Portland, OR 97211', insurance: 'Providence Health', provider: 'Dr. Sarah Patel', lastVisit: '2026-05-02', nextAppointment: '2026-07-02', status: 'active' },
  { id: 'P012', mrn: 'MRN-88483', firstName: 'Thomas', lastName: 'Wilson', dob: '1960-06-30', gender: 'Male', bloodType: 'B+', allergies: ['Iodine'], conditions: ['Prostate Cancer (in remission)', 'Hyperlipidemia'], medications: [{ name: 'Rosuvastatin', dosage: '10mg', frequency: 'Once daily' }], phone: '(555) 234-0987', email: 'thomas.wilson@email.com', address: '963 Pinecone Way, Portland, OR 97212', insurance: 'Medicare', provider: 'Dr. Vibhanshu Buldeo', lastVisit: '2026-04-20', nextAppointment: '2026-07-30', status: 'active' },
  { id: 'P013', mrn: 'MRN-88484', firstName: 'Amanda', lastName: 'Taylor', dob: '1995-12-01', gender: 'Female', bloodType: 'O-', allergies: ['Sulfa', 'Eggs'], conditions: ['UTI', 'Anxiety'], medications: [{ name: 'Sertraline', dosage: '100mg', frequency: 'Once daily' }], phone: '(555) 345-8765', email: 'amanda.taylor@email.com', address: '159 Cedar Path, Portland, OR 97213', insurance: 'Kaiser Permanente', provider: 'Dr. Michael Torres', lastVisit: '2026-05-13', nextAppointment: '', status: 'active' },
  { id: 'P014', mrn: 'MRN-88485', firstName: 'George', lastName: 'Clark', dob: '1982-09-28', gender: 'Male', bloodType: 'A+', allergies: [], conditions: ['Sleep Apnea', 'GERD'], medications: [{ name: 'Omeprazole', dosage: '20mg', frequency: 'Once daily' }], phone: '(555) 456-7654', email: 'george.clark@email.com', address: '753 Willow Ave, Portland, OR 97214', insurance: 'United Healthcare', provider: 'Dr. Emily Park', lastVisit: '2026-03-20', nextAppointment: '', status: 'inactive' },
  { id: 'P015', mrn: 'MRN-88486', firstName: 'Olivia', lastName: 'Martinez', dob: '2005-07-16', gender: 'Female', bloodType: 'AB+', allergies: ['Peanuts', 'Shellfish'], conditions: ['Type 1 Diabetes', 'Celiac Disease'], medications: [{ name: 'Insulin Lispro', dosage: 'Units per sliding scale', frequency: 'With meals' }, { name: 'Insulin Glargine', dosage: '20 units', frequency: 'Once daily at bedtime' }], phone: '(555) 567-6543', email: 'olivia.martinez@email.com', address: '444 Hemlock St, Portland, OR 97215', insurance: 'Blue Cross BCBS', provider: 'Dr. Sarah Patel', lastVisit: '2026-05-11', nextAppointment: '2026-06-18', status: 'active' },
]

export const appointments: Appointment[] = [
  { id: 'A001', patientId: 'P001', patientName: 'Sarah Chen', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', type: 'followup', date: '2026-06-15', time: '09:00', duration: 30, status: 'scheduled', notes: 'BP check, medication review', location: 'Suite 210', vitals: undefined },
  { id: 'A002', patientId: 'P003', patientName: 'Emily Johnson', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Pulmonology', type: 'checkup', date: '2026-06-10', time: '10:00', duration: 30, status: 'confirmed', notes: 'Asthma follow-up, spirometry', location: 'Suite 210' },
  { id: 'A003', patientId: 'P008', patientName: 'Michael Patel', doctorName: 'Dr. Michael Torres', department: 'Orthopedics', type: 'followup', date: '2026-06-05', time: '11:30', duration: 45, status: 'confirmed', notes: 'ACL rehab assessment', location: 'Suite 340' },
  { id: 'A004', patientId: 'P002', patientName: 'Robert Martinez', doctorName: 'Dr. Emily Park', department: 'Cardiology', type: 'checkup', date: '2026-05-22', time: '08:30', duration: 30, status: 'completed', notes: 'Annual cardiac evaluation. BP 128/78', location: 'Suite 220', vitals: { bp: '128/78', hr: 72, temp: 98.6, weight: 195 } },
  { id: 'A005', patientId: 'P005', patientName: 'Maria Garcia', doctorName: 'Dr. Emily Park', department: 'Endocrinology', type: 'followup', date: '2026-05-22', time: '09:30', duration: 30, status: 'completed', notes: 'Thyroid panel reviewed. TSH 2.4', location: 'Suite 220', vitals: { bp: '132/84', hr: 76, temp: 98.4, weight: 168 } },
  { id: 'A006', patientId: 'P009', patientName: 'Jennifer Williams', doctorName: 'Dr. Sarah Patel', department: 'Neurology', type: 'consultation', date: '2026-05-22', time: '14:00', duration: 45, status: 'in_progress', notes: 'Migraine management plan', location: 'Suite 410' },
  { id: 'A007', patientId: 'P007', patientName: 'Linda Brown', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', type: 'followup', date: '2026-05-23', time: '09:00', duration: 30, status: 'scheduled', notes: 'CHF exacerbation monitoring', location: 'Suite 210' },
  { id: 'A008', patientId: 'P013', patientName: 'Amanda Taylor', doctorName: 'Dr. Michael Torres', department: 'Internal Medicine', type: 'lab', date: '2026-05-23', time: '10:30', duration: 20, status: 'scheduled', notes: 'CBC and CMP follow-up', location: 'Lab B' },
  { id: 'A009', patientId: 'P015', patientName: 'Olivia Martinez', doctorName: 'Dr. Sarah Patel', department: 'Endocrinology', type: 'followup', date: '2026-06-18', time: '15:00', duration: 45, status: 'scheduled', notes: 'Diabetes management, A1C check', location: 'Suite 410' },
  { id: 'A010', patientId: 'P004', patientName: 'James Thompson', doctorName: 'Dr. Michael Torres', department: 'Internal Medicine', type: 'checkup', date: '2026-06-22', time: '13:00', duration: 30, status: 'scheduled', notes: 'Annual physical', location: 'Suite 340' },
  { id: 'A011', patientId: 'P010', patientName: 'William Davis', doctorName: 'Dr. Emily Park', department: 'Rheumatology', type: 'followup', date: '2026-05-24', time: '11:00', duration: 30, status: 'scheduled', notes: 'Uric acid levels review', location: 'Suite 220' },
  { id: 'A012', patientId: 'P011', patientName: 'Sophia Anderson', doctorName: 'Dr. Sarah Patel', department: 'Pediatrics', type: 'checkup', date: '2026-07-02', time: '09:30', duration: 30, status: 'scheduled', notes: '2-year well child visit', location: 'Suite 410' },
  { id: 'A013', patientId: 'P006', patientName: 'David Kim', doctorName: 'Dr. Sarah Patel', department: 'Dermatology', type: 'followup', date: '2026-05-21', time: '16:00', duration: 30, status: 'completed', notes: 'Eczema improved, continue treatment', location: 'Suite 410', vitals: { bp: '118/72', hr: 68, temp: 98.2, weight: 165 } },
  { id: 'A014', patientId: 'P012', patientName: 'Thomas Wilson', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Oncology', type: 'followup', date: '2026-04-20', time: '14:30', duration: 60, status: 'completed', notes: 'PSA undetectable, continue surveillance', location: 'Suite 210' },
  { id: 'A015', patientId: 'P014', patientName: 'George Clark', doctorName: 'Dr. Emily Park', department: 'Pulmonology', type: 'checkup', date: '2026-03-20', time: '10:00', duration: 30, status: 'no_show', notes: 'No show - reschedule requested', location: 'Suite 220' },
  { id: 'A016', patientId: 'P002', patientName: 'Robert Martinez', doctorName: 'Dr. Emily Park', department: 'Cardiology', type: 'emergency', date: '2026-05-18', time: '03:30', duration: 120, status: 'completed', notes: 'Chest pain - ruled out MI. Discharged stable.', location: 'ED Bay 4', vitals: { bp: '155/92', hr: 98, temp: 98.8, weight: 198 } },
  { id: 'A017', patientId: 'P001', patientName: 'Sarah Chen', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', type: 'checkup', date: '2026-05-10', time: '09:00', duration: 30, status: 'completed', notes: 'BP 124/78. Lisinopril continued.', location: 'Suite 210', vitals: { bp: '124/78', hr: 70, temp: 98.4, weight: 145 } },
  { id: 'A018', patientId: 'P013', patientName: 'Amanda Taylor', doctorName: 'Dr. Michael Torres', department: 'Internal Medicine', type: 'consultation', date: '2026-05-13', time: '11:00', duration: 30, status: 'completed', notes: 'UTI resolved. Anxiety management discussed.', location: 'Suite 340', vitals: { bp: '120/76', hr: 82, temp: 98.6, weight: 138 } },
  { id: 'A019', patientId: 'P007', patientName: 'Linda Brown', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', type: 'surgery', date: '2026-06-01', time: '07:00', duration: 180, status: 'scheduled', notes: 'Cardiac catheterization', location: 'OR 3' },
  { id: 'A020', patientId: 'P003', patientName: 'Emily Johnson', doctorName: 'Dr. Vibhanshu Buldeo', department: 'Pulmonology', type: 'lab', date: '2026-04-25', time: '08:00', duration: 15, status: 'completed', notes: 'Pulmonary function test completed', location: 'Pulmonary Lab' },
]

export const medicalRecords: MedicalRecord[] = [
  { id: 'MR001', patientId: 'P001', type: 'lab_result', title: 'Comprehensive Metabolic Panel', description: 'CMP results within normal limits. Glucose 95 mg/dL, Creatinine 0.9 mg/dL.', date: '2026-05-10', provider: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR002', patientId: 'P001', type: 'lab_result', title: 'Lipid Panel', description: 'Total Cholesterol 180, LDL 98, HDL 52, Triglycerides 150.', date: '2026-05-10', provider: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR003', patientId: 'P005', type: 'lab_result', title: 'Thyroid Panel', description: 'TSH 2.4 mIU/L, Free T4 1.1 ng/dL. Within normal limits.', date: '2026-05-12', provider: 'Dr. Emily Park', department: 'Endocrinology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR004', patientId: 'P007', type: 'imaging', title: 'Chest X-Ray PA & Lateral', description: 'Mild cardiomegaly. No acute pulmonary pathology. Small pleural effusion noted.', date: '2026-05-05', provider: 'Dr. Vibhanshu Buldeo', department: 'Radiology', status: 'final', attachments: 3, url: '#' },
  { id: 'MR005', patientId: 'P007', type: 'lab_result', title: 'BNP Level', description: 'BNP 845 pg/mL. Elevated, consistent with CHF exacerbation.', date: '2026-05-05', provider: 'Dr. Vibhanshu Buldeo', department: 'Cardiology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR006', patientId: 'P008', type: 'imaging', title: 'MRI Left Knee', description: 'Complete tear of the anterior cruciate ligament. Grade II medial meniscus tear.', date: '2026-05-14', provider: 'Dr. Michael Torres', department: 'Radiology', status: 'final', attachments: 4, url: '#' },
  { id: 'MR007', patientId: 'P002', type: 'imaging', title: 'Echocardiogram', description: 'LVEF 55%. Mild mitral regurgitation. No wall motion abnormalities.', date: '2026-05-08', provider: 'Dr. Emily Park', department: 'Cardiology', status: 'final', attachments: 2, url: '#' },
  { id: 'MR008', patientId: 'P015', type: 'lab_result', title: 'Hemoglobin A1C', description: 'HbA1C 7.2%. Improved from 8.1%. Continue current insulin regimen.', date: '2026-05-11', provider: 'Dr. Sarah Patel', department: 'Endocrinology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR009', patientId: 'P015', type: 'lab_result', title: 'Celiac Panel', description: 'Tissue transglutaminase IgA 12 U/mL. Negative. Gluten-free diet compliance good.', date: '2026-05-11', provider: 'Dr. Sarah Patel', department: 'Gastroenterology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR010', patientId: 'P004', type: 'lab_result', title: 'Hepatitis B Surface Antibody', description: 'Positive - immune status confirmed. >12 mIU/mL.', date: '2026-05-01', provider: 'Dr. Michael Torres', department: 'Internal Medicine', status: 'final', attachments: 1, url: '#' },
  { id: 'MR011', patientId: 'P009', type: 'note', title: 'Neurology Consult Note', description: 'Patient reports 2-3 migraines per week. Start Sumatriptan PRN. Recommend headache diary.', date: '2026-04-30', provider: 'Dr. Sarah Patel', department: 'Neurology', status: 'final', attachments: 0, url: '#' },
  { id: 'MR012', patientId: 'P006', type: 'note', title: 'Dermatology Progress Note', description: 'Eczema lesions improved with Triamcinolone. Continue emollients. Follow-up in 3 months.', date: '2026-04-15', provider: 'Dr. Sarah Patel', department: 'Dermatology', status: 'final', attachments: 0, url: '#' },
  { id: 'MR013', patientId: 'P012', type: 'lab_result', title: 'PSA Test', description: 'PSA 0.8 ng/mL. Undetectable. Continue annual surveillance.', date: '2026-04-20', provider: 'Dr. Vibhanshu Buldeo', department: 'Oncology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR014', patientId: 'P010', type: 'lab_result', title: 'Uric Acid Level', description: 'Uric Acid 6.8 mg/dL. Near goal. Continue Allopurinol 300mg.', date: '2026-05-07', provider: 'Dr. Emily Park', department: 'Rheumatology', status: 'final', attachments: 1, url: '#' },
  { id: 'MR015', patientId: 'P003', type: 'lab_result', title: 'Pulmonary Function Test', description: 'FEV1 85% predicted. Mild obstruction. Albuterol response positive.', date: '2026-04-25', provider: 'Dr. Vibhanshu Buldeo', department: 'Pulmonology', status: 'final', attachments: 2, url: '#' },
  { id: 'MR016', patientId: 'P002', type: 'vaccination', title: 'Influenza Vaccine', description: 'Seasonal flu vaccine administered. Lot #FLU2026-384.', date: '2025-10-15', provider: 'Nurse Amy', department: 'Internal Medicine', status: 'final', attachments: 0, url: '#' },
  { id: 'MR017', patientId: 'P011', type: 'vaccination', title: 'MMR Vaccine', description: 'Measles, Mumps, Rubella vaccine administered. Lot #MMR-2291.', date: '2026-05-02', provider: 'Nurse Amy', department: 'Pediatrics', status: 'final', attachments: 0, url: '#' },
  { id: 'MR018', patientId: 'P013', type: 'lab_result', title: 'Urinalysis with Culture', description: 'Urine culture positive for E. coli >100k CFU/mL. Sensitive to Nitrofurantoin.', date: '2026-05-13', provider: 'Dr. Michael Torres', department: 'Internal Medicine', status: 'final', attachments: 1, url: '#' },
  { id: 'MR019', patientId: 'P002', type: 'imaging', title: 'CT Coronary Angiogram', description: 'Calcium score 340. Moderate stenosis in LAD (60%). Medical management recommended.', date: '2026-04-28', provider: 'Dr. Emily Park', department: 'Radiology', status: 'final', attachments: 6, url: '#' },
  { id: 'MR020', patientId: 'P005', type: 'report', title: 'DEXA Scan', description: 'BMD T-score -1.8 (osteopenia). Continue calcium and vitamin D supplementation.', date: '2026-03-10', provider: 'Dr. Emily Park', department: 'Endocrinology', status: 'final', attachments: 2, url: '#' },
  { id: 'MR021', patientId: 'P004', type: 'prescription', title: 'Ibuprofen 600mg', description: 'Take 1 tablet three times daily as needed for back pain. Dispense #60.', date: '2026-05-01', provider: 'Dr. Michael Torres', department: 'Internal Medicine', status: 'final', attachments: 0, url: '#' },
  { id: 'MR022', patientId: 'P014', type: 'lab_result', title: 'Hemoglobin A1C', description: 'HbA1C 5.6%. Normal. No diabetes screening needed.', date: '2026-03-20', provider: 'Dr. Emily Park', department: 'Internal Medicine', status: 'preliminary', attachments: 1, url: '#' },
  { id: 'MR023', patientId: 'P009', type: 'imaging', title: 'MRI Brain Without Contrast', description: 'Normal brain MRI. No mass, hemorrhage, or ischemic changes. Incidental small meningioma noted.', date: '2026-04-29', provider: 'Dr. Sarah Patel', department: 'Radiology', status: 'final', attachments: 5, url: '#' },
  { id: 'MR024', patientId: 'P003', type: 'lab_result', title: 'IgE Level', description: 'Total IgE 245 IU/mL. Elevated. Consistent with allergic asthma.', date: '2026-04-25', provider: 'Dr. Vibhanshu Buldeo', department: 'Pulmonology', status: 'amended', attachments: 1, url: '#' },
  { id: 'MR025', patientId: 'P012', type: 'report', title: 'Pathology Report - Prostate Biopsy', description: 'Negative for malignancy. Benign prostatic tissue. No evidence of recurrence.', date: '2024-11-15', provider: 'Dr. Vibhanshu Buldeo', department: 'Pathology', status: 'final', attachments: 3, url: '#' },
]

export const prescriptions: Prescription[] = [
  { id: 'RX001', patientId: 'P001', patientName: 'Sarah Chen', medication: 'Lisinopril', dosage: '10mg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 3, prescribedBy: 'Dr. Vibhanshu Buldeo', date: '2026-03-15', status: 'active', notes: 'Take in the morning', pharmacy: 'CVS Pharmacy #4521' },
  { id: 'RX002', patientId: 'P001', patientName: 'Sarah Chen', medication: 'Metformin', dosage: '500mg', frequency: 'Twice daily', route: 'Oral', quantity: 60, refills: 3, prescribedBy: 'Dr. Vibhanshu Buldeo', date: '2026-03-15', status: 'active', notes: 'Take with meals', pharmacy: 'CVS Pharmacy #4521' },
  { id: 'RX003', patientId: 'P002', patientName: 'Robert Martinez', medication: 'Atorvastatin', dosage: '20mg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 5, prescribedBy: 'Dr. Emily Park', date: '2026-01-10', status: 'active', notes: 'Take in the evening', pharmacy: 'Walgreens #2876' },
  { id: 'RX004', patientId: 'P002', patientName: 'Robert Martinez', medication: 'Omeprazole', dosage: '40mg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 2, prescribedBy: 'Dr. Emily Park', date: '2026-02-20', status: 'active', notes: 'Take before breakfast', pharmacy: 'Walgreens #2876' },
  { id: 'RX005', patientId: 'P003', patientName: 'Emily Johnson', medication: 'Albuterol HFA', dosage: '90mcg', frequency: 'As needed', route: 'Inhalation', quantity: 1, refills: 2, prescribedBy: 'Dr. Vibhanshu Buldeo', date: '2026-04-25', status: 'active', notes: '2 puffs every 4 hours as needed for wheezing', pharmacy: 'Rite Aid #1192' },
  { id: 'RX006', patientId: 'P005', patientName: 'Maria Garcia', medication: 'Levothyroxine', dosage: '75mcg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 3, prescribedBy: 'Dr. Emily Park', date: '2026-02-01', status: 'active', notes: 'Take on empty stomach 30min before breakfast', pharmacy: 'CVS Pharmacy #4521' },
  { id: 'RX007', patientId: 'P007', patientName: 'Linda Brown', medication: 'Furosemide', dosage: '40mg', frequency: 'Twice daily', route: 'Oral', quantity: 60, refills: 1, prescribedBy: 'Dr. Vibhanshu Buldeo', date: '2026-05-05', status: 'active', notes: 'Monitor weight daily', pharmacy: 'Walgreens #2876' },
  { id: 'RX008', patientId: 'P007', patientName: 'Linda Brown', medication: 'Tiotropium', dosage: '18mcg', frequency: 'Once daily', route: 'Inhalation', quantity: 1, refills: 0, prescribedBy: 'Dr. Vibhanshu Buldeo', date: '2025-11-01', status: 'expired', notes: 'Expired - needs re-evaluation', pharmacy: 'Walgreens #2876' },
  { id: 'RX009', patientId: 'P004', patientName: 'James Thompson', medication: 'Ibuprofen', dosage: '600mg', frequency: 'Three times daily', route: 'Oral', quantity: 90, refills: 0, prescribedBy: 'Dr. Michael Torres', date: '2026-03-01', status: 'discontinued', notes: 'Discontinued - GI concerns', pharmacy: 'Rite Aid #1192' },
  { id: 'RX010', patientId: 'P015', patientName: 'Olivia Martinez', medication: 'Insulin Glargine', dosage: '20 units', frequency: 'Once daily at bedtime', route: 'Subcutaneous', quantity: 1, refills: 3, prescribedBy: 'Dr. Sarah Patel', date: '2026-04-01', status: 'active', notes: 'Administer at 9 PM. Rotate injection sites.', pharmacy: 'CVS Pharmacy #4521' },
  { id: 'RX011', patientId: 'P010', patientName: 'William Davis', medication: 'Allopurinol', dosage: '300mg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 3, prescribedBy: 'Dr. Emily Park', date: '2026-04-07', status: 'active', notes: 'Take after meals', pharmacy: 'Walgreens #2876' },
  { id: 'RX012', patientId: 'P013', patientName: 'Amanda Taylor', medication: 'Sertraline', dosage: '100mg', frequency: 'Once daily', route: 'Oral', quantity: 30, refills: 2, prescribedBy: 'Dr. Michael Torres', date: '2026-05-13', status: 'pending', notes: 'New prescription - pending pharmacy verification', pharmacy: 'Rite Aid #1192' },
]

export const messages: Message[] = [
  { id: 'M001', from: 'Dr. Emily Park', to: 'Dr. Vibhanshu Buldeo', subject: 'Cardiology consult for Robert Martinez', content: 'Jim, I am requesting a cardiology consult for Robert Martinez (MRN-88473). His recent CT angiogram shows moderate LAD stenosis. Would like your opinion on medical vs. interventional management.', timestamp: '2026-05-20T14:32:00', priority: 'urgent', read: false, category: 'clinical', patientName: 'Robert Martinez' },
  { id: 'M002', from: 'Lab Results System', to: 'Dr. Sarah Patel', subject: 'Critical Lab Result - Olivia Martinez', content: 'CRITICAL ALERT: Olivia Martinez (MRN-88486) Glucose 45 mg/dL at 08:15. Fingerstick confirmed. Patient contacted. Instructed to take 15g fast-acting glucose. Repeat glucose at 09:00 was 82 mg/dL.', timestamp: '2026-05-22T09:30:00', priority: 'critical', read: false, category: 'lab', patientName: 'Olivia Martinez' },
  { id: 'M003', from: 'Billing Department', to: 'Dr. Michael Torres', subject: 'Insurance Pre-Authorization - ACL Repair', content: 'Pre-authorization request for Michael Patel (MRN-88479) ACL repair has been approved by Aetna. Authorization #AUTH-88479-ACL. Surgery scheduled for June 5.', timestamp: '2026-05-21T11:15:00', priority: 'routine', read: true, category: 'billing', patientName: 'Michael Patel' },
  { id: 'M004', from: 'Nurse Amy Johnson', to: 'Dr. Vibhanshu Buldeo', subject: 'Linda Brown - Weight Gain Noted', content: 'Dr. Wilson, Linda Brown (MRN-88478) has gained 5 lbs since last visit. +1 pitting edema noted in lower extremities. May need diuretic adjustment.', timestamp: '2026-05-22T07:45:00', priority: 'urgent', read: false, category: 'clinical', patientName: 'Linda Brown' },
  { id: 'M005', from: 'Pharmacy - CVS #4521', to: 'Dr. Sarah Patel', subject: 'Refill Request - Insulin Lispro', content: 'Refill request for Olivia Martinez (MRN-88486): Insulin Lispro (Humalog) 1 box. Current prescription has 0 refills remaining. Please authorize refill.', timestamp: '2026-05-21T16:00:00', priority: 'routine', read: true, category: 'clinical', patientName: 'Olivia Martinez' },
  { id: 'M006', from: 'Dr. Michael Torres', to: 'Dr. Sarah Patel', subject: 'Migraine Treatment Guidelines', content: 'Sarah, I have a patient with refractory migraines. Would you recommend starting a CGRP inhibitor given the frequency and severity? Wanted to run this by you given your neuro expertise.', timestamp: '2026-05-19T15:20:00', priority: 'routine', read: true, category: 'clinical' },
  { id: 'M007', from: 'Scheduling System', to: 'Dr. Emily Park', subject: 'Appointment Reminder - Tomorrow Schedule', content: 'You have 4 appointments scheduled for tomorrow (May 23): 08:30 - David Kim (Room 410), 09:30 - Sarah Chen (Room 210), 11:00 - William Davis (Room 220), 14:00 - New Patient (Room 340).', timestamp: '2026-05-22T17:00:00', priority: 'routine', read: false, category: 'administrative' },
  { id: 'M008', from: 'HR Department', to: 'All Providers', subject: 'Mandatory HIPAA Training - June 2026', content: 'Annual HIPAA compliance training must be completed by June 30, 2026. The online module takes approximately 45 minutes. Please complete at your earliest convenience.', timestamp: '2026-05-18T09:00:00', priority: 'routine', read: true, category: 'administrative' },
  { id: 'M009', from: 'Radiology Department', to: 'Dr. Vibhanshu Buldeo', subject: 'CT Chest Results - Linda Brown', content: 'CT chest completed on Linda Brown (MRN-88478). Moderate pleural effusion noted. No pulmonary embolism. Report will be finalized within 24 hours.', timestamp: '2026-05-22T13:00:00', priority: 'urgent', read: false, category: 'lab', patientName: 'Linda Brown' },
  { id: 'M010', from: 'Dr. Vibhanshu Buldeo', to: 'Dr. Emily Park', subject: 'Re: Cardiology consult for Robert Martinez', content: 'Emily, reviewed the CT angiogram. Given 60% LAD stenosis with preserved LVEF, I recommend continuing optimal medical therapy. Add metoprolol 25mg daily. Repeat stress echo in 6 months.', timestamp: '2026-05-20T16:45:00', priority: 'routine', read: true, category: 'clinical', patientName: 'Robert Martinez' },
  { id: 'M011', from: 'Lab Results System', to: 'Dr. Michael Torres', subject: 'Lab Results - Amanda Taylor', content: 'Amanda Taylor (MRN-88484): Urine culture final. E. coli >100k CFU/mL. Sensitive: Nitrofurantoin, Cephalexin. Resistant: Amoxicillin.', timestamp: '2026-05-14T10:30:00', priority: 'routine', read: true, category: 'lab', patientName: 'Amanda Taylor' },
  { id: 'M012', from: 'IT Support', to: 'All Staff', subject: 'EHR System Maintenance - Sunday 2 AM', content: 'The EHR system will be undergoing planned maintenance on Sunday, May 25 from 2:00 AM to 4:00 AM. The system will be unavailable during this time. Please plan accordingly.', timestamp: '2026-05-22T08:00:00', priority: 'routine', read: false, category: 'administrative' },
  { id: 'M013', from: 'Dr. Sarah Patel', to: 'Dr. Michael Torres', subject: 'Re: Migraine Treatment Guidelines', content: 'Michael, for refractory migraines with 2+ attacks per week, I would recommend starting a CGRP antagonist (e.g., Erenumab 70mg monthly). Monitor for response in 3 months.', timestamp: '2026-05-20T09:10:00', priority: 'routine', read: true, category: 'clinical' },
  { id: 'M014', from: 'External Lab - Quest Diagnostics', to: 'Dr. Emily Park', subject: 'Lab Results - William Davis', content: 'William Davis (MRN-88481): Uric acid 6.8 mg/dL. Lipid panel: TC 190, LDL 110, HDL 45, TG 175. Liver function normal.', timestamp: '2026-05-21T14:00:00', priority: 'routine', read: false, category: 'lab', patientName: 'William Davis' },
  { id: 'M015', from: 'Billing Department', to: 'Dr. Vibhanshu Buldeo', subject: 'Coding Query - CHF Encounter', content: 'Regarding Linda Brown (MRN-88478) visit on 5/5: could you clarify if this was acute-on-chronic CHF exacerbation or routine follow-up? Diagnosis code I50.9 vs I50.22.', timestamp: '2026-05-19T11:30:00', priority: 'routine', read: true, category: 'billing', patientName: 'Linda Brown' },
]

export const telemedicineSessions: TelemedicineSession[] = [
  { id: 'T001', patientName: 'Sarah Chen', doctorName: 'Dr. Vibhanshu Buldeo', date: '2026-05-22', time: '14:00', status: 'scheduled', duration: 30, type: 'video', notes: 'Follow-up BP check via video', recording: true },
  { id: 'T002', patientName: 'Emily Johnson', doctorName: 'Dr. Vibhanshu Buldeo', date: '2026-05-22', time: '15:00', status: 'in_progress', duration: 30, type: 'video', notes: 'Asthma symptom review', recording: true },
  { id: 'T003', patientName: 'David Kim', doctorName: 'Dr. Sarah Patel', date: '2026-05-21', time: '10:00', status: 'completed', duration: 20, type: 'phone', notes: 'Eczema treatment response - improved', recording: false },
  { id: 'T004', patientName: 'Maria Garcia', doctorName: 'Dr. Emily Park', date: '2026-05-23', time: '11:00', status: 'scheduled', duration: 30, type: 'video', notes: 'Thyroid medication review', recording: true },
  { id: 'T005', patientName: 'Jennifer Williams', doctorName: 'Dr. Sarah Patel', date: '2026-05-20', time: '16:00', status: 'completed', duration: 25, type: 'video', notes: 'Migraine follow-up - Sumatriptan working well', recording: false },
  { id: 'T006', patientName: 'James Thompson', doctorName: 'Dr. Michael Torres', date: '2026-05-25', time: '09:00', status: 'scheduled', duration: 30, type: 'phone', notes: 'Anxiety medication check-in', recording: false },
  { id: 'T007', patientName: 'George Clark', doctorName: 'Dr. Emily Park', date: '2026-04-10', time: '14:30', status: 'cancelled', duration: 30, type: 'video', notes: 'Cancelled - patient rescheduled', recording: false },
  { id: 'T008', patientName: 'Amanda Taylor', doctorName: 'Dr. Michael Torres', date: '2026-05-26', time: '10:30', status: 'scheduled', duration: 20, type: 'phone', notes: 'UTI treatment follow-up', recording: false },
]
